name: 'Basic build process of libskk using autotools'
description: 'Set up user and build directories, build, and run tests'

runs:
  using: composite
  steps:
    - name: Create user and directories
      run: $GITHUB_WORKSPACE/build/setup-wrapper.sh
      shell: bash

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        NOCONFIGURE=1 ./autogen.sh
        cd $GITHUB_WORKSPACE/$BUILDDIR
        $GITHUB_WORKSPACE/build/run-wrapper.sh $GITHUB_WORKSPACE/configure --prefix=$GITHUB_WORKSPACE/$INSTALLDIR --libdir=$GITHUB_WORKSPACE/$INSTALLDIR/lib $BUILD_OPTS
        $GITHUB_WORKSPACE/build/run-wrapper.sh make -j$(nproc) V=1
      shell: bash

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/$BUILDDIR
        $GITHUB_WORKSPACE/build/run-wrapper.sh make check -j$(nproc) V=1
        ret=$?
        if test $ret -ne 0; then
          cat $GITHUB_WORKSPACE/$BUILDDIR/test-suite.log
          exit $ret
        fi
      shell: bash

    - name: Distcheck
      if: ${{ env.DISTCHECK != 0 }}
      run: |
        cd $GITHUB_WORKSPACE/$BUILDDIR
        if [ "$RUNNER_OS" = "Linux" ]; then
          $GITHUB_WORKSPACE/build/run-wrapper.sh make distcheck -j$(nproc) V=1
        fi
      shell: bash

    - name: Install
      run: |
        cd $GITHUB_WORKSPACE/$BUILDDIR
        make install
        make installcheck
      shell: bash
