.\"                                      Hey, EMACS: -*- nroff -*-
.TH LIBSKK 1 "5 Jan 2012"
.SH NAME
skkfep \- Japanese SKK input method on text terminal
.SH SYNOPSIS
.B skkfep
.br
.SH DESCRIPTION
\fBskkfep\fP is a tool that allows to use Japanese input method called
SKK (Simple Kana to Kanji conversion program) on ANSI compliant text
terminals.
.PP
More information about the SKK input method itself can be found at:
\m[blue]\fB\%http://openlab.jp/skk/\fR\m[]\&
.SH AUTHOR
libskk was written by Daiki Ueno <ueno@unixuser.org>.
