name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILDDIR: "builddir"
  INSTALLDIR: "installdir"
  RUNUSER: "user"
  PROFILE: "testable"

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      MESON_BUILD_OPTS: -Ddocs=enabled -Dfep=enabled
    container:
      image: ghcr.io/ueno/libskk:master
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/basic-meson

  abi:
    runs-on: ubuntu-latest
    env:
      MESON_BUILD_OPTS: -Ddocs=disabled -Dfep=enabled
    container:
      image: ghcr.io/ueno/libskk:master
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/basic-meson
      - name: Check out fedora/43/x86_64
        run: |
          git config --global --add safe.directory /__w/libskk/libskk
          git branch fedora/43/x86_64 origin/fedora/43/x86_64
      - name: Check ABI compatibility
        run: |
          git worktree add abi fedora/43/x86_64
          abidiff --no-added-syms abi/usr/lib64/libskk.so.0/*.xml $GITHUB_WORKSPACE/$INSTALLDIR/lib/libskk.so.0
    
  asan:
    runs-on: ubuntu-latest
    env:
      MESON_BUILD_OPTS: -Ddocs=disabled -Dfep=enabled -Db_sanitize=address
    container:
      image: ghcr.io/ueno/libskk:master
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/basic-meson

  ubsan:
    runs-on: ubuntu-latest
    env:
      MESON_BUILD_OPTS: -Ddocs=disabled -Dfep=enabled -Db_sanitize=undefined
    container:
      image: ghcr.io/ueno/libskk:master
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/basic-meson
